### ISSUE TITLE
还有一个问题就是就是普通用户登录后不需要输入密码

### ISSUE THREAD

**Issue by hanliwy** [Arvintian/chatgpt-web#4]
我有aaa与bbb两个账号密码都一样。
我通过/login调出登录框登录aaa输入密码登录后，提问一个问题后，继续输入/login调出登录框后，输入bbb账户名后直接回车，就可以登录到bbb账户了。。。

**Comment by Arvintian** [comment]
这个应该是浏览器basic auth默认的行为，一般用户也就一个账号吧
