### ISSUE TITLE
dockerfile 用不了

### ISSUE THREAD

**Issue by YangHaHabiu** [Arvintian/chatgpt-web#5]
dockerfile 用不了

**Comment by Arvintian** [comment]
执行make package呢？

**Comment by YangHaHabiu** [comment]
没执行个过make package,我是想着二开的就试了下dockerfile 发现部署不了,不过用你的docker镜像可以部署起来

**Comment by YangHaHabiu** [comment]
有部署教程不?

**Comment by Arvintian** [comment]
直接docker build不行，编译打包参考makefile就可以
